### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import pandas as pd
import numpy as np

In [23]:
N=10
np.linspace(N-1, 0, num=N, dtype=int)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [40]:
N=5
diag=np.diag(np.linspace(N, 0, num=N+1, dtype=int), k=0)
total=0
for i in range(N):
    total+=diag[i,i]
print(diag, '; sum=', total)

[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]] ; sum= 15


### Задание 3
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [41]:
import pandas as pd

In [73]:
data = pd.read_csv('ratings.csv')

In [58]:
data.head()

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [75]:
data[data['rating']==5.0]['movieId'].value_counts().head(1)

318    170
Name: movieId, dtype: int64

### Задание 4
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [76]:
data = pd.read_csv('/home/yellow/Загрузки/5_Python_5_numpy_pandas/power.csv')

In [77]:
data.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [81]:
#найдем названий стран
data[ data['country'].str.contains('Est', case=False) ]['country'].unique()

array(['Estonia', 'State of Palestine', 'Timor-Leste'], dtype=object)

In [92]:
#отфильтруем по странам
data_1=data[ (data['country']=='Latvia') | (data['country']=='Estonia') | (data['country']=='Lithuania') ]

In [95]:
#отфильтруем по категориям
data_2=data_1[((data_1['category']==4) | (data_1['category']==12)| (data_1['category']==21))]

In [96]:
#отфильтруем по годам
data_3=data_2[((data_2['year']>=2005) & (data_2['year']<=2010))]

In [98]:
#отфильтруем по кол-ву
data_4=data_3[(data_3['quantity']>=0)]

In [100]:
#посчитаем сумму кол-ва
data_4['quantity'].sum()

240580.0

### Задание 5
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [102]:
from numpy import linalg

# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

# значения в правой части уравнения

b = np.array( [4, 12, -3] )

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [103]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True